# Generated by Django 5.2.4 on 2025-08-06 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='img')),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('blog_slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('0', 'DRAFT'), ('1', 'PUBLISH')], default=0, max_length=1)),
                ('section', models.CharField(choices=[('Recent', 'Recent'), ('Publish', 'Publish'), ('Trending', 'Trending')], max_length=100)),
                ('main_post', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='App.category')),
            ],
        ),
    ]
