# Generated by Django 5.2.4 on 2025-08-18 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_posts_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='section',
        ),
    ]
